# Generated by Django 3.2.7 on 2021-09-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_cricao',
            new_name='data_criacao',
        ),
    ]
